######################################################################
# Automatically generated by qmake (2.01a) Sat Sep 27 00:41:07 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT += network webkit  xml
# Input
HEADERS += MyQLineEdit.h myqttest.h youdao.h  xml/ParseXML.h
FORMS += youdao.ui
SOURCES += main.cpp MyQLineEdit.cpp myqttest.cpp youdao.cpp xml/ParseXML.cpp
